### ISSUE TITLE
Bug(s) in declared vars?

### ISSUE THREAD

**Issue by Zueuk** [kobalicek/mathpresso#5]
Hello!

It seems that the declared vars work in a strange way. I tried to swap values of x and y via a temporary variable t, and here's what I ended up with:

x=1; y=2; var t=x; t
1.000000

x=1; y=2; var t=x; x=y; t
2.000000

**Comment by Zueuk** [comment]
It seems that for some reason vars are read-only, but they do not always generate errors about this:

var t=1; t=2
ERROR: Invalid binary operation '='.

x=1; var t=x; t=2; t
1.000000

var t=1; t=x
[mathpresso] Assertion failed at E:\MathPresso\mathpresso-master\src\mathpresso\mpcompiler.cpp (line 463):
[mathpresso] varNode->getNodeType() == kAstNodeVar

**Comment by kobalicek** [comment]
Should by fixed, check it out and reopen if not. Also, more test cases welcome :)

**Comment by Zueuk** [comment]
Now assignment makes variables constant :-o they can even infect each other:

x=y
0.000000
y=x
0.000000
x=1
1.000000
x=1
NodeType: 5
ERROR: Can't assign to a non-variable.
x=y
NodeType: 5
ERROR: Can't assign to a non-variable.
y=x
1.000000
y=x
NodeType: 5
ERROR: Can't assign to a non-variable.

**Comment by kobalicek** [comment]
I'm gonna write more tests first, you are right, it's messed up.

**Comment by kobalicek** [comment]
Should be fixed.

**Comment by Zueuk** [comment]
Assignment to normal variables still doesn't work properly: try entering "x=1" two times in mpeval

**Comment by Zueuk** [comment]
Variables are not becoming constant now, but any changes to them stay inside of the expression:

x=1; x
1.000000

x
0.000000

**Comment by kobalicek** [comment]
Should be fine now, can you confirm?

**Comment by Zueuk** [comment]
Seems to be working now!
